In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/Latest Covid-19 India Status.csv')
display(data)

,State/UTs,Total Cases,Active,Discharged,Deaths,Active Ratio,Discharge Ratio,Death Ratio,Population
0,Andaman and Nicobar,10766,0,10637,129,0.00,98.80,1.20,100896618
1,Andhra Pradesh,2340676,0,2325943,14733,0.00,99.37,0.63,128500364
2,Arunachal Pradesh,67049,0,66753,296,0.00,99.56,0.44,658019
3,Assam,746159,5,738119,8035,0.00,98.92,1.08,290492
4,Bihar,855267,1,842952,12314,0.00,98.56,1.44,40100376
5,Chandigarh,100693,0,99508,1185,0.00,98.82,1.18,30501026
6,Chhattisgarh,1187695,0,1173505,14190,0.00,98.81,1.19,28900667
7,Dadra and Nagar Haveli and Daman and Diu,11592,0,11588,4,0.00,99.97,0.03,231502578
8,Delhi,2040910,14,2014230,26666,0.00,98.69,1.31,773997
9,Goa,263346,3,259329,4014,0.00,98.47,1.52,3772103
10,Gujarat,1291383,5,1280299,11079,0.00,99.14,0.86,70400153
11,Haryana,1078903,27,1068121,10755,0.00,99.00,1.00,7503010
12,Himachal Pradesh,322905,4,318660,4241,0.00,98.69,1.31,3436948
13,Jammu and Kashmir,482023,0,477231,4792,0.00,99.01,0.99,66001
14,Jharkhand,443826,1,438491,5334,0.00,98.80,1.20,124904071
15,Karnataka,4088769,12,4048399,40358,0.00,99.01,0.99,1711947
16,Kerala,6907241,18,6835181,72042,0.00,98.96,1.04,91702478
17,Ladakh,29602,0,29371,231,0.00,99.22,0.78,4184959
18,Lakshadweep,11415,0,11363,52,0.00,99.54,0.46,11700099
19,Madhya Pradesh,1056351,0,1045565,10786,0.00,98.98,1.02,14999397
20,Maharashtra,8171048,214,8022276,148558,0.00,98.18,1.82,399001
21,Manipur,140034,0,137885,2149,0.00,98.47,1.53,47099270
22,Meghalaya,96983,3,95352,1628,0.00,98.32,1.68,79502477
23,Mizoram,239560,1,238825,734,0.00,99.69,0.31,1308967
24,Nagaland,36033,0,35251,782,0.00,97.83,2.17,38157311
25,Odisha,1348409,59,1339135,9215,0.00,99.31,0.68,19301096
26,Puducherry,177547,0,175566,1981,0.00,98.88,1.12,2073074
27,Punjab,793644,1233,773073,19338,0.16,97.41,2.44,34698876
28,Rajasthan,1326465,2,1316727,9736,0.00,99.27,0.73,1521992
29,Sikkim,44927,4,44422,501,0.01,98.88,1.12,83697770
30,Tamil Nadu,3610655,5,3572569,38081,0.00,98.95,1.05,35998752
31,Telengana,844432,8,840313,4111,0.00,99.51,0.49,69599762
32,Tripura,108493,1,107550,942,0.00,99.13,0.87,1646050
33,Uttar Pradesh,2145431,57,2121662,23712,0.00,98.89,1.11,1158040
34,Uttarakhand,452571,0,444803,7768,0.00,98.28,1.72,85002417
35,West Bengal,2126282,135,2104592,21555,0.01,98.98,1.01,32199722

In [ ]:
import pandas as pd
data = pd.read_csv('/content/Latest Covid-19 India Status.csv')
df=pd.DataFrame(data)
display(df.drop(["Total Cases", "Active","Discharged","Discharge Ratio","Active Ratio","Population",],axis=1))

                                   State/UTs  Deaths  Death Ratio
0                        Andaman and Nicobar     129         1.20
1                             Andhra Pradesh   14733         0.63
2                          Arunachal Pradesh     296         0.44
3                                      Assam    8035         1.08
4                                      Bihar   12314         1.44
5                                 Chandigarh    1185         1.18
6                               Chhattisgarh   14190         1.19
7   Dadra and Nagar Haveli and Daman and Diu       4         0.03
8                                      Delhi   26666         1.31
9                                        Goa    4014         1.52
10                                   Gujarat   11079         0.86
11                                   Haryana   10755         1.00
12                          Himachal Pradesh    4241         1.31
13                         Jammu and Kashmir    4792         0.99
14                                 Jharkhand    5334         1.20
15                                 Karnataka   40358         0.99
16                                    Kerala   72042         1.04
17                                    Ladakh     231         0.78
18                               Lakshadweep      52         0.46
19                            Madhya Pradesh   10786         1.02
20                               Maharashtra  148558         1.82
21                                   Manipur    2149         1.53
22                                 Meghalaya    1628         1.68
23                                   Mizoram     734         0.31
24                                  Nagaland     782         2.17
25                                    Odisha    9215         0.68
26                                Puducherry    1981         1.12
27                                    Punjab   19338         2.44
28                                 Rajasthan    9736         0.73
29                                    Sikkim     501         1.12
30                                Tamil Nadu   38081         1.05
31                                 Telengana    4111         0.49
32                                   Tripura     942         0.87
33                             Uttar Pradesh   23712         1.11
34                               Uttarakhand    7768         1.72
35                               West Bengal   21555         1.01

In [ ]:
import pandas as pd
data = pd.read_csv('/content/Latest Covid-19 India Status.csv')
Recovery=pd.DataFrame(data)
display(Recovery.drop(["Total Cases", "Active","Deaths","Death Ratio","Active Ratio","Population",],axis=1))

                                   State/UTs  Discharged  Discharge Ratio
0                        Andaman and Nicobar       10637            98.80
1                             Andhra Pradesh     2325943            99.37
2                          Arunachal Pradesh       66753            99.56
3                                      Assam      738119            98.92
4                                      Bihar      842952            98.56
5                                 Chandigarh       99508            98.82
6                               Chhattisgarh     1173505            98.81
7   Dadra and Nagar Haveli and Daman and Diu       11588            99.97
8                                      Delhi     2014230            98.69
9                                        Goa      259329            98.47
10                                   Gujarat     1280299            99.14
11                                   Haryana     1068121            99.00
12                          Himachal Pradesh      318660            98.69
13                         Jammu and Kashmir      477231            99.01
14                                 Jharkhand      438491            98.80
15                                 Karnataka     4048399            99.01
16                                    Kerala     6835181            98.96
17                                    Ladakh       29371            99.22
18                               Lakshadweep       11363            99.54
19                            Madhya Pradesh     1045565            98.98
20                               Maharashtra     8022276            98.18
21                                   Manipur      137885            98.47
22                                 Meghalaya       95352            98.32
23                                   Mizoram      238825            99.69
24                                  Nagaland       35251            97.83
25                                    Odisha     1339135            99.31
26                                Puducherry      175566            98.88
27                                    Punjab      773073            97.41
28                                 Rajasthan     1316727            99.27
29                                    Sikkim       44422            98.88
30                                Tamil Nadu     3572569            98.95
31                                 Telengana      840313            99.51
32                                   Tripura      107550            99.13
33                             Uttar Pradesh     2121662            98.89
34                               Uttarakhand      444803            98.28
35                               West Bengal     2104592            98.98

In [32]:
import pandas as pd
data = pd.read_csv('/content/covid-19-daily-cases-data.csv')

Daily_Cases=pd.DataFrame(data)
display(Daily_Cases.drop(["units", "notes",],axis=1))

      data_as_on                category     value
0     10-06-2024    Total Positive Cases  45040074
1     10-06-2024  Number of Active cases       206
2     10-06-2024         Total Recovered  44506249
3     10-06-2024            Total Deaths    533619
4     09-06-2024    Total Positive Cases  45040060
...          ...                     ...       ...
6275  25-03-2020            Total Deaths        10
6276  24-03-2020    Total Positive Cases       536
6277  24-03-2020  Number of Active cases       487
6278  24-03-2020         Total Recovered        39
6279  24-03-2020            Total Deaths        10

[6280 rows x 3 columns]